Make wrapper scripts work as python or sh.
Change-Id: I054fe4d6a08221814292702ef96f65517b304cb0

diff --git a/debian/bin/kg-manage b/debian/bin/kg-manage
--- a/debian/bin/kg-manage
+++ b/debian/bin/kg-manage
@@ -1,14 +1,19 @@
 #!/bin/sh
-
-EXE="kg-manage"
-
-if test -x /usr/bin/python2.7 && test -e /usr/share/python-karaage/bin/$EXE
+shell_code=''' '
+# shell code
+if command -v python3 > /dev/null && test -e /usr/share/python3-karaage
 then
-    exec python2.7 /usr/share/python-karaage/bin/$EXE "$@"
-elif test -x /usr/bin/python3 && test -e /usr/share/python3-karaage/bin/$EXE
+    exec python3 "$0" "$@"
+elif command -v python2.7 > /dev/null && test -e /usr/share/python-karaage
 then
-    exec python3 /usr/share/python3-karaage/bin/$EXE "$@"
+    exec python2.7 "$0" "$@"
 else
-    echo "Cannot find installed version of $EXE." >&2
+    echo "Cannot find installed version of karaage." >&2
     exit 1
 fi
+
+python_code='''
+# python code
+# ONLY use DOUBLE quotes <"> after this line
+exec(open("/usr/share/python-karaage/bin/kg-manage", "rb").read())
+# End of Python code. Do not modify this line. #'
